# Generated by Django 4.0.5 on 2022-07-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.TextField(default='available', null=True),
        ),
    ]
